### ISSUE TITLE
Report Detail - Responsive Issue #1

### ISSUE THREAD

**Issue by cfreder2** [ndoit/fenrir#136] opened 2016-05-16 14:25 UTC
![image](https://cloud.githubusercontent.com/assets/407661/15292298/7812c4ee-1b50-11e6-9e0a-3ffafd44226b.png)

**Comment by RyanSnodgrass** [comment] 2016-05-25 14:35
duplicate of #180

**Closed by RyanSnodgrass** 2016-05-25 14:35 UTC
Labels: Priority 3
