### ISSUE TITLE
Open Dataset in Tableau: Login Required

### ISSUE THREAD

**Issue by EvanGranthamBrown** [ndoit/fenrir#181] opened 2016-05-19 19:30 UTC
When the user is not logged in to Tableau Server and clicks the "TABLEAU" button on the dataset detail page, nothing happens; the workbook does not download. Need to implement a similar solution to the report page.

**Comment by RyanSnodgrass** [comment] 2016-05-19 20:33
Possible duplicate of #133 ?

**Comment by EvanGranthamBrown** [comment] 2016-05-23 19:36
Waiting on solution to the report/CAS auth issue.

**Closed** 2016-05-25 14:26 UTC
Labels: Priority 1
